version: 2.1

jobs:
  test:
    docker:
      - image: "cimg/node:17.2"
    steps:
      - checkout
      - run: cd app && npm run test
  build:
    docker:
      - image: cimg/go:1.17
        auth:
          username: deekode
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t deekode/survey-app:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push deekode/survey-app:$TAG
workflows:
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test